// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ApolloLinks         = require("reason-apollo/src/ApolloLinks.bs.js");
var ReasonApollo        = require("reason-apollo/src/ReasonApollo.bs.js");
var ApolloInMemoryCache = require("reason-apollo/src/ApolloInMemoryCache.bs.js");

var inMemoryCache = ApolloInMemoryCache.createInMemoryCache(/* Some */[(function (obj) {
          return obj.id;
        })], /* None */0, /* () */0);

var httpLink = ApolloLinks.createHttpLink("http://swapi.apis.guru/", /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var apolloClient = ReasonApollo.createApolloClient(inMemoryCache, httpLink, /* None */0, /* None */0, /* None */0, /* None */0, /* () */0);

var Instance = ReasonApollo.CreateClient(/* module */[/* apolloClient */apolloClient]);

exports.inMemoryCache = inMemoryCache;
exports.httpLink      = httpLink;
exports.Instance      = Instance;
/* inMemoryCache Not a pure module */
